### ISSUE TITLE
Publish to 0.9.1 release to jcenter & maven central

### ISSUE THREAD

**Issue by bootstraponline** [appium/droiddriver#1]
Publishing to jcenter & maven central will allow easier integration with Gradle builds.

- Depends on versioning #11
- Depends on gradle build support https://github.com/appium/droiddriver/issues/13
- Depends on new package name https://github.com/appium/droiddriver/issues/12

**Comment by bootstraponline** [comment]
I'm working with jcenter to figure out why the metadata is incorrect. Once that's resolved then there'll be a beta release of 0.9.1 which the examples can use until the official release occurs.

**Comment by bootstraponline** [comment]
I found the issue & submitted a fix for review.
https://android-review.googlesource.com/132790

**Comment by bootstraponline** [comment]
@ddkjin should I release master as 0.9.1? Other than the comment on gerrit about the Google build breaking, it seems ready to go.

**Comment by ddkjin** [comment]
The issues in internal repo have been resolved. I think the commit won't be reverted, so it's good to go. Thanks!

**Comment by bootstraponline** [comment]
0.9.1 has been published!
https://bintray.com/appium/maven/io.appium%3Adroiddriver/0.9.1/view
