### ISSUE TITLE
Setup media for dev discussion

### ISSUE THREAD

**Issue by 0x1mason** [appium/droiddriver#18]
@jlipps @bootstraponline @ddkjin I created a google discussion group, droiddriver-dev, but then remembered some people really dislike google groups.  Are people cool with that?  Or are there preferred media?

**Comment by bootstraponline** [comment]
I think google groups is not perfect however there seem to be limited options for mailing lists. I'm fine with it since espresso is also using a google group.

**Comment by bootstraponline** [comment]
We could try using the issue tracker as a discussion group. Apparently [other projects](https://github.com/nodeschool/discussions) have had success with this model.

**Comment by bootstraponline** [comment]
I think the consensus is to try the issue tracker as a discussion group replacement. If it doesn't work out then we could always look at other options.

**Comment by jlipps** [comment]
:+1:
