### ISSUE TITLE
Versioning model

### ISSUE THREAD

**Issue by 0x1mason** [appium/droiddriver#19]
@jlipps @ddkjin @bootstraponline Might be a little late since I think 1.0 is about to become official.  Also this might have already been discussed but I missed it do to matters elsewhere demanding attention.  Apologies if I'm late to the the program.

Anyway, are we using [semantic versioning](http://semver.org/)?  If so, we'll want to start organizing milestones to be sure we're not breaking the API between major releases. Eg, we had discussed changing `newDriver` to `createSingleton`.  Assuming we add the new function, we'll need to mark `newDriver` with a warning as deprecated and create tickets to remove the deprecated functions entirely in 2.0.

**Comment by bootstraponline** [comment]
So far the only decision is that 1.0 will be the version for the first release (once the package name is updated #12). I think we should use semver. What do you think @ddkjin?

**Comment by ddkjin** [comment]
semver looks good - a formal spec turns common practice into a standard.
As Eric pointed out, we have some pending updates to the API (though they're small). Shall the first release be 0.9.1 so that we can remove the deprecated API now?

**Comment by bootstraponline** [comment]
Sure, that works.

**Comment by bootstraponline** [comment]
I think semver + starting at 0.9.1 resolves this issue.
