### ISSUE TITLE
Is the min sdk req 7 or 12?

### ISSUE THREAD

**Issue by bootstraponline** [appium/droiddriver#22]
In build.gradle I see `minSdkVersion 12 // TODO: need to support SDK 9?` which is higher than Espresso supports. I thought DD supports as low as API 7?

**Comment by ddkjin** [comment]
InstrumentationDriver relies only on Instrumentation, so it only needs API 7 (as Espresso does).
But if minSdkVersion is set to 7, there are lint warnings/errors b/c some places use higher level APIs w/o guarding code.

**Comment by bootstraponline** [comment]
droiddriver from jcenter can only be used with SDK 12 or higher because of the `minSdkVersion` in build.gradle. I think we should set this to 7 and fix the warnings/errors by adding code guards?

**Comment by ddkjin** [comment]
Changed minSdkVersion to 8 (Froyo) in https://android-review.googlesource.com/#/c/133752/
In fact I think practically soon 9 (Gingerbread) may not have significant amount of users.
