### ISSUE TITLE
Easier way to find by resourceId

### ISSUE THREAD

**Issue by bootstraponline** [appium/droiddriver#27]
It'd be nice to support finding by resource id ints instead of being limited to strings.

```java
   String resourceId(int rID) {
        return getTargetContext().getResources().getResourceName(rID);
    }

// DroidDrivers.get().on(By.resourceId(resourceId(rID)));
```

**Comment by ddkjin** [comment]
I have always wanted to add this, but it depends on an instance of Context.
I think By should not depend on Context. Maybe we can add this method to DroidDrivers, where  Instrumentation is available, but it's a little weird. Now I only mentioned this way in helpers/package-info.java.

**Comment by bootstraponline** [comment]
I guess having the helper method in the end user test code is the cleanest approach then.
