### ISSUE TITLE
Keep JavaDoc up-to-date

### ISSUE THREAD

**Issue by ddkjin** [appium/droiddriver#29]
http://appium.github.io/droiddriver/javadoc/ still reflects the old package name before 0.9.1
I think it needs to be in sync with either the latest release or the TOT snapshot. Or does it need to be versioned?

**Comment by bootstraponline** [comment]
I'll work on setting up automatic javadoc publishing. I published that one manually which is why it's out of date.

**Comment by bootstraponline** [comment]
Automatic javadoc on Jenkins from the master branch is setup.

- https://team-appium.ci.cloudbees.com/view/DroidDriver/job/DroidDriver_Publish_OPE/
- http://appium.github.io/droiddriver/javadoc/

**Comment by ddkjin** [comment]
Links in http://appium.github.io/droiddriver/javadoc/ return 404. PTAL.

**Comment by bootstraponline** [comment]
Fixed. For some reason they were ignored. Adding -f --all to the git add command resolved the issue in Jenkins.

**Comment by bootstraponline** [comment]
https://team-appium.ci.cloudbees.com/view/DroidDriver/job/DroidDriver_Javadoc_OPE/28/console
