### ISSUE TITLE
UIAutomator 2.0 & DroidDriver

### ISSUE THREAD

**Issue by bootstraponline** [appium/droiddriver#35]
@ddkjin What impact does [UIAutomator 2.0](https://plus.google.com/+AndroidDevelopers/posts/WCWANrPkRxg) have on DroidDriver?

- [UIAutomator 2.0 API docs](http://developer.android.com/reference/android/support/test/uiautomator/package-summary.html)
- [Testing Support Library docs](http://developer.android.com/tools/testing-support-library/index.html)

**Comment by bootstraponline** [comment]
Also if someone knows where to find the source code for `Android Testing Support Library` that'd be helpful.

**Comment by ddkjin** [comment]
I think both are under https://android.googlesource.com/platform/frameworks/testing/+/master, but the latest commit was 5 months old. You can compare it with the public doc to make sure.

**Comment by bootstraponline** [comment]
They're not publishing the source code. I checked what's in the Android SDK and it [doesn't match](https://github.com/bootstraponline/android_support_test/tree/master/test/uiautomator/uiautomator-v18/2.0.0). SDK includes `uiautomator-v18-2.0.0.aar` which isn't in AOSP.

**Comment by bootstraponline** [comment]
There are more differences such as the [UiObject2](http://developer.android.com/reference/android/support/test/uiautomator/UiObject2Condition.html) classes not existing. I guess at some point they'll release the code. It's annoying uiautomator 2.0 is the only one with the source jar excluded in the Android SDK.

**Comment by ddkjin** [comment]
Maybe this is a good reason to use DroidDriver instead for it's truly open-sourced :)

The source in AOSP does not match, but looking at the API I don't expect fundamental change from 1.0, except for running tests through Instrumentation.

**Comment by bootstraponline** [comment]
What do you think about DD updating to use uiautomator 2? Other than the package name change, it looks like it's backwards compatible.

I think it'd be great to position DD as a way to leverage all the work going into the 	android.support.test.* namespace (uiautomator2, new junit4 test runner, etc.) while at the same time being a true open source project. It also fills the gap of an API that works across uiautomator and old devices. Espresso is super different from uiautomator in terms of API.

**Comment by ddkjin** [comment]
Can you elaborate how to do that?
There was a proposal to merge DD and uiautomator, but I don't see how to achieve that - API is quite different though not as different as Espresso's. The implementation is also quite different though both are based on the UiAutomation API

**Comment by bootstraponline** [comment]
Ah. I was confused a bit between `UiAutomation` and `uiautomator`. It looks like there's no `uiautomator` code in droiddriver so the v2 release of uiautomator isn't related to DD at all. Appium uses v1 of uiautomator and it has a bunch of issues.

Once uiautomator v2 has an open repo then I'll look into exploring possibilities. They might have some interesting code even if a full merge doesn't make sense.

**Comment by bootstraponline** [comment]
The branch in use for Espresso 2.0 is [android-support-test](https://android.googlesource.com/platform/frameworks/testing/+/android-support-test). One of the devs confirmed that uiautomator 2 isn't released to AOSP.
