### ISSUE TITLE
"test watcher" support in droiddriver?

### ISSUE THREAD

**Issue by bootstraponline** [appium/droiddriver#37]
UiAutomator has support for [test watchers](https://developer.android.com/reference/android/support/test/uiautomator/UiWatcher.html). In appium we're using this to [automatically dismiss system crashes alerts, app not responding, etc](https://github.com/appium/appium/blob/7d085163f0b09a245b48b41a887b460a5515984e/lib/devices/android/bootstrap/src/com/android/uiautomator/common/UiWatchers.java). Is there a similar concept in droiddriver?

**Comment by ddkjin** [comment]
Yes, and actually DD has two types of watchers:
[Poller.PollingListener](http://appium.github.io/droiddriver/javadoc/io/appium/droiddriver/Poller.PollingListener.html) and [Poller.TimeoutListener](http://appium.github.io/droiddriver/javadoc/io/appium/droiddriver/Poller.TimeoutListener.html)
And a util class [PollingListeners](http://appium.github.io/droiddriver/javadoc/io/appium/droiddriver/helpers/PollingListeners.html)

**Comment by bootstraponline** [comment]
Thanks!
