### ISSUE TITLE
Unable to find instrumentation info

### ISSUE THREAD

**Issue by bootstraponline** [appium/droiddriver#7]
I see this error when running droiddriver tests on bitbar using API 21 devices. I think this is bitbar specific so I'm not too concerned. The same test passes locally on an API 21 device.

> Unable to find instrumentation info for: ComponentInfo{com.example.android.testing.espresso.BasicSample.test/android.test.InstrumentationTestRunner}

**Comment by bootstraponline** [comment]
droiddriver works on testobject.

- [report](https://app.testobject.com/#/share/e2134a13-2ac3-4c91-bd22-ed0caa696bdb)

**Comment by ddkjin** [comment]
The message tells the problem: android.test.InstrumentationTestRunner should not be the instrumentation. It's specified in either build (testInstrumentationRunner) or AndroidManifest.xml and in the current code it should be android.support.test.runner.AndroidJUnitRunner.
I don't know bitbar but I agree it's not a problem in BasicSample. I heard some TaaS providers limit the runner to InstrumentationTestRunner and maybe this is such a case.
