### ISSUE TITLE
Borrow closeSoftKeyboard from Espresso

### ISSUE THREAD

**Issue by bootstraponline** [appium/droiddriver#8]
As droiddriver lacks the ability to close the software keyboard, it'd be nice to borrow some parts of Espresso such as the `closeSoftKeyboard` method. The easy way to do this is just include the entire Espresso jar in the test project, then we're not maintaining additional code.

It'd probably be better to add an extra Utils class and copy only the bits of Espresso that make sense for DroidDriver.

**Comment by bootstraponline** [comment]
- [CloseKeyboardAction.java from Espresso 2.0](https://github.com/bootstraponline/espresso_2_clone/blob/cd69a5086db74158e19cfd91eb39a9d522dd3c4f/espresso-core-2.0-sources/android/support/test/espresso/action/CloseKeyboardAction.java#L49)

**Comment by bootstraponline** [comment]
I ended up using the espresso jar plus a [custom fix](https://github.com/appium/droiddriver_examples/blob/1ad1f46f03c91c33c232f18bd6d4c34e62e4dec8/espresso_sample/espresso/BasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/CloseSoftKeyboard.java) for the flakiness problem. This seems like something that droiddriver should provide.

**Comment by bootstraponline** [comment]
@ddkjin Do you have any thoughts on using `hideSoftInputFromWindow` to close the keyboard? The Espresso work around is nice however it's kind of a hack since not everyone will be using Espresso with droiddriver.

**Comment by ddkjin** [comment]
In fact droiddriver-0.9.1 does not open the soft keyboard with the implementation of BaseUiElement.setText(). Is this issue still important?
If the soft keyboard is open in some cases, usually you can close it with
 driver.getUiDevice().pressBack();
I can port Espresso CloseKeyboardAction easily, but I think it might be confusing if the pressBack alternative already works. One advantage of pressBack is that it works cross-apps (using UiAutomationDriver) while CloseKeyboardAction only works within AUT (using InstrumentationDriver).

**Comment by bootstraponline** [comment]
> In fact droiddriver-0.9.1 does not open the soft keyboard with the implementation of BaseUiElement.setText(). Is this issue still important?

Yes, if a keyboard is present then there should be a way to dismiss it reliably.

> If the soft keyboard is open in some cases, usually you can close it with
> driver.getUiDevice().pressBack();

The problem is in keyboard detection. If the back key is pressed and the keyboard isn't actually open then the AUT will change state and even possibly exit. The close keyboard method needs to:

- Successfully detect when the keyboard is present or not (can't do this by sending the back button)
- Close the keyboard
- Wait until the keyboard has successfully closed (espresso fails here, the work around is a static sleep) before returning

> can port Espresso CloseKeyboardAction easily, but I think it might be confusing if the pressBack alternative already works. One advantage of pressBack is that it works cross-apps (using UiAutomationDriver) while CloseKeyboardAction only works within AUT (using InstrumentationDriver).

I think porting Espresso CloseKeyboardAction is worthwhile. I don't see pressBack as a valid alternative for the following reasons:

- pressBack modifies the app even if the keyboard isn't present. hideKeyboard should be a no-op if there's no keyboard.
- pressBack doesn't wait for the keyboard to be dismissed, the back event fires and then it's up to luck if it actually dismissed the keyboard or not. We don't know if it succeeded.

I think the Espresso CloseKeyboardAction provides a good option that's a meaningful improvement to pressBack. pressBack will remain available so people can use that if it meets their requirements. It's worth nothing that two other frameworks (not including Espresso) include a close keyboard helper method not based on the back key press.

- [Calabash Android close keyboard (based on old robotium)](https://github.com/calabash/calabash-android/blob/5d50902bcbb6cd4f58fc8cd151bc344a933dc16f/ruby-gem/test-server/instrumentation-backend/src/sh/calaba/instrumentationbackend/actions/text/HideSoftKeyboard.java#L33)
- [Robotium close keyboard](https://github.com/RobotiumTech/robotium/blob/23ca3cd28d798a4c11d425a8bd67e29407b93919/robotium-solo/src/main/java/com/robotium/solo/DialogUtils.java#L166)

**Comment by ddkjin** [comment]
Added in https://android-review.googlesource.com/#/c/141641
I didn't provide a closeSoftKeyboard method in UiDevice or UiElement b/c this action is specific to InstrumentationDriver. If I implement closeSoftKeyboard for UiAutomationDriver as pressBack, the behavior is not consistent. When I cannot guarantee consistency, IMO it's better to let users decide and make the choice explicit.

**Comment by bootstraponline** [comment]
I agree.

**Comment by bootstraponline** [comment]
https://github.com/appium/droiddriver/commit/dfb7bd50344340bf195ad3ba1f7b33ff2957271a
